name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: rm -rf /var/www/unguka_rra/*
      - run: cp -r . /var/www/unguka_rra
